apiVersion: v1
kind: Service
metadata:
  name: note-server-service
  labels:
    app: note-server
spec:
  ports:
    - protocol: {{ .Values.mongodb.service.protocol }}
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
  selector:
    app: note-server
